### ISSUE TITLE
Exporting images

### ISSUE THREAD

**Issue by Mad880** [chipolux/disrev#1]
Hey there, I understand this repository hasn't been touched in a while but is it possible to export images from the game with this tool? Like the actual paintings seen in the game?

**Comment by chipolux** [comment]
It can! (Kind of, in a maybe not super useful way...) They are just resources (`entries` I think I call them here) that you can extract. They'll be in a format specially made for game assets, and figuring out what painting is which resource may be a challenge but they'll probably be marked as `images`.

See [this breakdown of file types](https://github.com/chipolux/disrev/blob/main/docs/type-src-dst-combos.csv#L403) I found in... Dishonored 2 I think. The format there is: Type is a tag in the resource file, SrcExt is the file extension before being compiled/bundled into the game, DstExt is the file extension inside the game bundle and is the format the data will be in if you extract it.

I bet you paintings were `.png`, `.bmp`,  or `.tga` before, and if you extract them they'll be `.bimage7` files. The tricky part then is converting a `.bimage7` file into an image you can actually use.

It doesn't look like I investigated this format much, but if you extract some and figure out how to decode them it'd be great to add a decoder/encoder here to allow swapping/modding what's in the paintings and textures etc. They likely share a lot of DNA, and may be identical to [`.tga / BIMAGE` files packed into doom resources](https://wiki.eternalmods.com/books/8-reverse-engineering-file-formats/page/tga-file-extension-bimage) since the dishonored engine seems to be a modified id tech engine.

**Comment by Mad880** [comment]
Thank you so much for your response!
